#!/bin/sh

# Check only two argument is passed in
if [ $# -ne 2 ]
then
   echo "Usage: ./assemble [execName] [ARMCode.s]"
   exit 1
fi

# Assemble for rpi arm architecture
cmd="arm-linux-gnueabi-gcc -mcpu=arm1176jzf-s -mtune=arm1176jzf-s -o "
cmd+=$1  # first argument: exec filename
cmd+=" "
cmd+=$2  # second argument: .s file

docker run -it --rm -v $(pwd):/src --entrypoint bash jqpoon/arm_compile_emulate:working -c "$cmd"
